import React, { memo } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';
import { cn } from '../../../lib/cn';

export type MessageRole = 'user' | 'foli' | 'assistant' | 'bot';

interface MemoizedMarkdownProps {
  content: string;
  role?: MessageRole | 'document';
}

export const MemoizedMarkdown = memo(function MemoizedMarkdown({
  content,
  role = 'foli',
}: MemoizedMarkdownProps) {
  const isUserMessage = role === 'user';

  return (
    <div
      className={cn(
        "prose prose-slate max-w-none text-sm leading-relaxed",
        isUserMessage ? "prose-invert text-white" : "text-slate-900"
      )}
    >
      <ReactMarkdown
        remarkPlugins={[remarkMath]}
        rehypePlugins={[rehypeKatex]}
        components={{
        h3: ({ children, ...props }) => {
          const text = React.Children.toArray(children).join('');
          const isAISuggestion = !isUserMessage && (text.includes('[AI 제안 초안]') || text.includes('[AI Draft Suggestion]'));

          if (isAISuggestion) {
            return (
              <h3
                {...props}
                className="mb-4 mt-8 flex items-center gap-2 rounded-xl border border-indigo-100 bg-indigo-50/50 px-3 py-2 text-sm font-bold text-indigo-700 shadow-sm"
              >
                <span className="inline-flex h-5 w-5 items-center justify-center rounded-lg bg-indigo-600 text-[10px] font-black text-white shadow-sm">AI</span>
                {children}
              </h3>
            );
          }

          return <h3 {...props} className={cn('mb-3 mt-6 text-lg font-black', isUserMessage ? 'text-white' : 'text-slate-900')} />;
        },
        p: ({ children, ...props }) => {
          const text = React.Children.toArray(children).join('');
          const isAINote =
            !isUserMessage &&
            (
              text.includes('유니폴리가 생성한 제안 문장입니다.')
              || text.includes('AI 제안')
              || text.includes('This text was generated by Foli')
              || text.includes('AI suggestion')
            );

          if (isAINote) {
            return (
              <p
                {...props}
                className="mb-5 rounded-xl border-l-4 border-indigo-200/50 bg-indigo-50/30 px-4 py-3 text-[14px] font-medium italic text-slate-700 shadow-sm"
              />
            );
          }

          return <p {...props} className={cn('text-[15px] leading-7 font-medium', isUserMessage ? 'whitespace-pre-wrap text-white' : 'text-slate-800')} />;
        },
        ul: ({ children, ...props }) => <ul {...props} className={cn("mb-4 ml-4 list-disc space-y-2", isUserMessage ? "text-white/90" : "text-slate-700")}>{children}</ul>,
        ol: ({ children, ...props }) => <ol {...props} className={cn("mb-4 ml-4 list-decimal space-y-2", isUserMessage ? "text-white/90" : "text-slate-700")}>{children}</ol>,
        li: ({ children, ...props }) => <li {...props} className="text-sm leading-relaxed">{children}</li>,
        code: ({ className, children, ...props }) => {
          const match = /language-(\w+)/.exec(className || '');
          const isInline = !match;
          return isInline ? (
            <code {...props} className="rounded bg-slate-100 px-1.5 py-0.5 font-mono text-xs font-bold text-indigo-600">
              {children}
            </code>
          ) : (
            <pre className="mt-2 overflow-x-auto rounded-xl bg-slate-900 p-4">
              <code {...props} className={cn('font-mono text-xs text-slate-200', className)}>
                {children}
              </code>
            </pre>
          );
        },
        strong: ({ children }) => <strong className={cn("font-extrabold", isUserMessage ? "text-white" : "text-indigo-600")}>{children}</strong>,
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
});
