import React, { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import {
  Bot,
  ChevronDown,
  ChevronUp,
  Download,
  Loader2,
  Save,
  Send,
  ShieldCheck,
  Sparkles,
  ToggleLeft,
  ToggleRight,
  User,
  WandSparkles,
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';
import { useLocation, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import confetti from 'canvas-confetti';
import { auth } from '../lib/firebase';
import { api, resolveApiBaseUrl } from '../lib/api';
import { cn } from '../lib/cn';
import { saveArchiveItem } from '../lib/archiveStore';
import { readQuestStart } from '../lib/questStart';
import { AdvancedPreview } from '../components/AdvancedPreview';
import { EvidenceDrawer } from '../components/EvidenceDrawer';
import {
  PageHeader,
  PrimaryButton,
  SecondaryButton,
  SectionCard,
  StatusBadge,
  SurfaceCard,
  WorkflowNotice,
} from '../components/primitives';
import {
  ensureThreeSuggestions,
  type GuidedTopicSelectionResponse,
  type GuidedTopicSuggestion,
  type GuidedTopicSuggestionResponse,
} from '../lib/guidedChat';
import {
  BLOCK_DEFINITIONS,
  WORKSHOP_MODE_OPTIONS,
  applyDraftPatch,
  createEmptyStructuredDraft,
  isPatchAcceptanceMessage,
  isSectionDraftIntent,
  markdownToStructuredDraft,
  normalizeStructuredDraft,
  structuredDraftToMarkdown,
  type WorkshopDraftAttribution,
  type WorkshopDraftPatchProposal,
  type WorkshopMode,
  type WorkshopStructuredDraftState,
} from '../lib/workshopCoauthoring';

const MemoizedMarkdown = memo(function MemoizedMarkdown({
  content,
  role = 'foli',
}: {
  content: string;
  role?: MessageRole | 'document';
}) {
  const isUserMessage = role === 'user';

  return (
    <div
      className={cn(
        "prose prose-slate max-w-none text-sm leading-relaxed",
        isUserMessage ? "prose-invert text-white" : "text-slate-900"
      )}
    >
      <ReactMarkdown
        remarkPlugins={[remarkMath]}
        rehypePlugins={[rehypeKatex]}
        components={{
        h3: ({ children, ...props }) => {
          const text = React.Children.toArray(children).join('');
          const isAISuggestion = !isUserMessage && (text.includes('[AI 제안 초안]') || text.includes('[AI Draft Suggestion]'));

          if (isAISuggestion) {
            return (
              <h3
                {...props}
                className="mb-4 mt-8 flex items-center gap-2 rounded-xl border border-[#004aad]/5 bg-[#004aad]/5 px-3 py-2 text-sm font-bold text-[#004aad]"
              >
                <span className="inline-flex h-5 w-5 items-center justify-center rounded-lg bg-[#004aad] text-[10px] font-black text-white">AI</span>
                {children}
              </h3>
            );
          }

          return <h3 {...props} className={cn('mb-3 mt-6 text-lg font-black', isUserMessage ? 'text-white' : 'text-slate-900')} />;
        },
        p: ({ children, ...props }) => {
          const text = React.Children.toArray(children).join('');
          const isAINote =
            !isUserMessage &&
            (text.includes('This text was generated by Foli') || text.includes('AI suggestion'));

          if (isAINote) {
            return (
              <p
                {...props}
                className="mb-5 rounded-lg border-l-4 border-[#004aad]/20 bg-[#004aad]/5 px-3 py-2 text-sm font-medium italic text-slate-700"
              />
            );
          }

          return <p {...props} className={cn('text-[15px] leading-7 font-medium', isUserMessage ? 'whitespace-pre-wrap text-white' : 'text-slate-800')} />;
        },
        ul: ({ children, ...props }) => <ul {...props} className={cn("mb-4 ml-4 list-disc space-y-2", isUserMessage ? "text-white/90" : "text-slate-700")}>{children}</ul>,
        ol: ({ children, ...props }) => <ol {...props} className={cn("mb-4 ml-4 list-decimal space-y-2", isUserMessage ? "text-white/90" : "text-slate-700")}>{children}</ol>,
        li: ({ children, ...props }) => <li {...props} className="text-sm leading-relaxed">{children}</li>,
        code: ({ className, children, ...props }) => {
          const match = /language-(\w+)/.exec(className || '');
          const isInline = !match;
          return isInline ? (
            <code {...props} className="rounded bg-slate-100 px-1.5 py-0.5 font-mono text-xs font-bold text-[#004aad]">
              {children}
            </code>
          ) : (
            <pre className="mt-2 overflow-x-auto rounded-xl bg-slate-900 p-4">
              <code {...props} className={cn('font-mono text-xs text-slate-200', className)}>
                {children}
              </code>
            </pre>
          );
        },
        strong: ({ children }) => <strong className={cn("font-bold", isUserMessage ? "text-white" : "text-[#004aad]")}>{children}</strong>,
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
});

export type QualityLevel = 'low' | 'mid' | 'high';
type MessageRole = 'user' | 'foli' | 'assistant' | 'bot';

interface Message {
  id: string;
  role: MessageRole;
  content: string;
  draftPatch?: WorkshopDraftPatchProposal;
  topicSubject?: string;
  topicSuggestions?: GuidedTopicSuggestion[];
}

interface DraftArtifact {
  id: string;
  report_markdown: string;
  visual_specs: any[];
  math_expressions: any[];
  evidence_map?: Record<string, any> | null;
  structured_draft?: WorkshopStructuredDraftState | null;
  updated_at?: string | null;
}

interface WorkshopSaveDraftResponse {
  status: string;
  message: string;
  saved_updated_at: string;
  structured_draft?: WorkshopStructuredDraftState | null;
}

interface WorkshopSessionResponse {
  id: string;
  project_id: string;
  quest_id: string | null;
  status: string;
  quality_level: QualityLevel;
  turns?: Array<{
    id: string;
    turn_type: string;
    speaker_role?: string;
    query?: string;
    response?: string;
    action_payload?: Record<string, unknown> | null;
  }>;
}

interface QualityLevelInfo {
  level: QualityLevel;
  label: string;
  emoji: string;
  color: string;
  description: string;
  detail: string;
  student_fit: string;
  safety_posture: string;
  authenticity_policy: string;
  hallucination_guardrail: string;
  advanced_features_allowed: boolean;
  minimum_turn_count: number;
  minimum_reference_count: number;
  render_threshold: number;
}

interface RenderRequirementInfo {
  required_context_score: number;
  minimum_turn_count: number;
  minimum_reference_count: number;
  current_context_score: number;
  current_turn_count: number;
  current_reference_count: number;
  can_render: boolean;
  missing: string[];
}

interface WorkshopStateResponse {
  session: WorkshopSessionResponse;
  starter_choices: any[];
  followup_choices: any[];
  message: string | null;
  quality_level_info?: QualityLevelInfo;
  available_quality_levels?: QualityLevelInfo[];
  render_requirements?: RenderRequirementInfo;
  latest_artifact: DraftArtifact | null;
}

interface GuidedChatStartResponse {
  greeting: string;
  project_id: string | null;
  evidence_gap_note: string | null;
  limited_mode?: boolean | null;
  limited_reason?: string | null;
  state_summary?: Record<string, unknown> | null;
}

interface StreamMetaPayload {
  profile?: string;
  limited_mode?: boolean;
  limited_reason?: string | null;
  coauthoring_mode?: WorkshopMode;
}

const QUALITY_META_MAP: Record<QualityLevel, { label: string; status: 'success' | 'active' | 'warning' }> = {
  low: { label: '빠른 응답', status: 'success' },
  mid: { label: '균형 모드', status: 'active' },
  high: { label: '심화 모드', status: 'warning' },
};

const GUIDED_CHAT_GREETING = '안녕하세요 어떤 주제로 보고서를 써볼까요?';

function normalizeGuidedSuggestions(response: GuidedTopicSuggestionResponse): GuidedTopicSuggestion[] {
  return ensureThreeSuggestions(response).suggestions.slice(0, 3);
}

function formatGuidedSuggestionMessage(response: GuidedTopicSuggestionResponse) {
  const suggestions = normalizeGuidedSuggestions(response);
  const lines = [
    `요청하신 '${response.subject}' 주제 기준으로 3가지 방향을 제안합니다.`,
    '',
    ...suggestions.flatMap((item, index) => {
      const chunk = [
        `${index + 1}. **${item.title}**`,
        `- 적합 이유: ${item.why_fit_student}`,
        `- 기록 연결: ${item.link_to_record_flow}`,
      ];
      if (item.link_to_target_major_or_university) {
        chunk.push(`- 목표 연결: ${item.link_to_target_major_or_university}`);
      }
      if (item.caution_note) {
        chunk.push(`- 주의: ${item.caution_note}`);
      }
      return chunk;
    }),
  ];
  if (response.evidence_gap_note) {
    lines.push('', `참고: ${response.evidence_gap_note}`);
  }
  lines.push('', '아래 카드에서 한 가지를 선택해주세요');
  return lines.join('\n');
}

function formatGuidedSelectionMessage(response: GuidedTopicSelectionResponse) {
  const lines = [
    `선택하신 주제는 **${response.selected_title}**입니다.`,
    '',
    response.guidance_message,
    '',
    '권장 분량:',
    ...response.recommended_page_ranges.map(
      range => `- ${range.label} (${range.min_pages}~${range.max_pages}p): ${range.why_this_length}`,
    ),
    '',
    '권장 개요:',
    ...response.recommended_outline.map(section => `- ${section.title}: ${section.purpose}`),
    '',
    '오른쪽 초안 패널에 스타트 초안을 채워 두었습니다. 다음 메시지로 세부 문단을 이어가 보세요',
  ];
  return lines.join('\n');
}

function resolveGuidedSelectionFromText(text: string, suggestions: GuidedTopicSuggestion[]): GuidedTopicSuggestion | null {
  if (!suggestions.length) {
    return null;
  }
  const normalized = text.trim().toLowerCase();
  if (!normalized) {
    return null;
  }
  const numberMatch = normalized.match(/^([1-3])$/);
  if (numberMatch) {
    const index = Number(numberMatch[1]) - 1;
    return suggestions[index] ?? null;
  }
  const topicIdMatch = normalized.match(/^topic-([1-3])$/);
  if (topicIdMatch) {
    const index = Number(topicIdMatch[1]) - 1;
    return suggestions[index] ?? null;
  }
  return (
    suggestions.find(
      item =>
        normalized === item.id.toLowerCase() ||
        normalized === item.title.toLowerCase() ||
        normalized.includes(item.title.toLowerCase()),
    ) ?? null
  );
}

function buildFoliFallback(message: string) {
  const clean = message.toLowerCase().trim();
  const greetings = ['hello', 'hi', 'hey', 'good morning', 'good evening'];

  if (greetings.some(token => clean.includes(token))) {
    return [
      'Hello. This is Uni Foli workshop support.',
      '',
      'Live AI generation is currently limited, but we can still continue with structure and editing guidance.',
    ].join('\n');
  }

  return [
    'Automatic grounding is temporarily limited.',
    '',
    'Please continue with this fallback checklist:',
    '1. Clarify your research question.',
    '2. List the evidence you already have in the uploaded record.',
    '3. Build a section-by-section draft outline.',
  ].join('\n');
}

function normalizeStructuredDraftPatch(value: unknown): WorkshopDraftPatchProposal | null {
  if (!value || typeof value !== 'object') return null;
  const candidate = value as Record<string, unknown>;
  const mode = candidate.mode;
  const blockId = candidate.block_id;
  const content = String(candidate.content_markdown || '').trim();
  const requiresApproval = Boolean(candidate.requires_approval ?? true);
  if (
    (mode !== 'planning' && mode !== 'outline' && mode !== 'section_drafting' && mode !== 'revision') ||
    !(
      blockId === 'title' ||
      blockId === 'introduction_background' ||
      blockId === 'body_section_1' ||
      blockId === 'body_section_2' ||
      blockId === 'body_section_3' ||
      blockId === 'conclusion_reflection_next_step'
    ) ||
    !content
  ) {
    return null;
  }

  return {
    mode,
    block_id: blockId,
    heading: candidate.heading ? String(candidate.heading) : undefined,
    content_markdown: content,
    rationale: candidate.rationale ? String(candidate.rationale) : undefined,
    evidence_boundary_note: candidate.evidence_boundary_note ? String(candidate.evidence_boundary_note) : undefined,
    requires_approval: requiresApproval,
  };
}

function extractPatchTagFromRaw(raw: string): { cleaned: string; patch: WorkshopDraftPatchProposal | null } {
  if (!raw) return { cleaned: '', patch: null };
  const match = raw.match(/\[DRAFT_PATCH\]([\s\S]*?)\[\/DRAFT_PATCH\]/i);
  if (!match?.[1]) {
    return { cleaned: raw.trim(), patch: null };
  }
  let payload = match[1].trim();
  if (payload.startsWith('```')) {
    payload = payload.replace(/^```(?:json)?/i, '').replace(/```$/i, '').trim();
  }
  let patch: WorkshopDraftPatchProposal | null = null;
  try {
    patch = normalizeStructuredDraftPatch(JSON.parse(payload));
  } catch {
    patch = null;
  }
  const cleaned = raw.replace(/\[DRAFT_PATCH\][\s\S]*?\[\/DRAFT_PATCH\]/gi, '').trim();
  return { cleaned, patch };
}

async function streamFoliReply(
  projectId: string | undefined,
  workshopId: string | undefined,
  message: string,
  draftSnapshotMarkdown: string | undefined,
  mode: WorkshopMode,
  structuredDraft: WorkshopStructuredDraftState | null,
  onDelta?: (delta: string) => void,
  onMeta?: (meta: StreamMetaPayload) => void,
  onDraftPatch?: (patch: WorkshopDraftPatchProposal) => void,
) {
  const baseUrl = resolveApiBaseUrl();
  const token = auth?.currentUser ? await auth.currentUser.getIdToken() : null;
  let response: Response;

  try {
    if (workshopId) {
      response = await fetch(`${baseUrl}/api/v1/workshops/${workshopId}/chat/stream`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
        body: JSON.stringify({
          message,
          draft_snapshot_markdown: draftSnapshotMarkdown,
          mode,
          structured_draft: structuredDraft ?? undefined,
        }),
      });
    } else {
      response = await fetch(`${baseUrl}/api/v1/drafts/chat/stream`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
        body: JSON.stringify({ project_id: projectId, message, reference_materials: [], draft_snapshot_markdown: draftSnapshotMarkdown }),
      });
    }
  } catch {
    if (!projectId && !workshopId) return buildFoliFallback(message);
    throw new Error('NETWORK_FAIL');
  }

  if (!response.ok || !response.body) {
    if (!projectId && !workshopId) return buildFoliFallback(message);
    if (response.status === 429) throw new Error('RATE_LIMIT');
    if (response.status === 401 || response.status === 403) throw new Error('AUTH_REQUIRED');
    throw new Error('STREAM_FAIL');
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder('utf-8');
  let full = '';
  let buffer = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const chunks = buffer.split('\n\n');
    buffer = chunks.pop() || '';

    for (const event of chunks) {
      const line = event.split('\n').find(item => item.startsWith('data:'));
      if (!line) continue;

      let payload: Record<string, unknown>;
      try {
        payload = JSON.parse(line.replace(/^data:\s*/, ''));
      } catch {
        continue;
      }

      if (payload.done) break;
      if (typeof payload.error === 'string' && payload.error.trim()) throw new Error(payload.error.trim());

      if (payload.meta && typeof payload.meta === 'object') {
        onMeta?.(payload.meta as StreamMetaPayload);
      }

      if (payload.draft_patch && typeof payload.draft_patch === 'object') {
        onDraftPatch?.(payload.draft_patch as WorkshopDraftPatchProposal);
      }

      if (typeof payload.token === 'string' && payload.token) {
        full += payload.token;
        onDelta?.(payload.token);
      }
    }
  }

  // Flush decoder tail bytes to avoid partial UTF-8 character truncation on stream end.
  buffer += decoder.decode();
  if (buffer.trim()) {
    const chunks = buffer.split('\n\n');
    for (const event of chunks) {
      const line = event.split('\n').find(item => item.startsWith('data:'));
      if (!line) continue;

      let payload: Record<string, unknown>;
      try {
        payload = JSON.parse(line.replace(/^data:\s*/, ''));
      } catch {
        continue;
      }

      if (payload.done) break;
      if (typeof payload.error === 'string' && payload.error.trim()) throw new Error(payload.error.trim());

      if (payload.meta && typeof payload.meta === 'object') {
        onMeta?.(payload.meta as StreamMetaPayload);
      }

      if (payload.draft_patch && typeof payload.draft_patch === 'object') {
        onDraftPatch?.(payload.draft_patch as WorkshopDraftPatchProposal);
      }

      if (typeof payload.token === 'string' && payload.token) {
        full += payload.token;
        onDelta?.(payload.token);
      }
    }
  }

  return full.trim();
}

const ChatBubble = memo(function ChatBubble({
  message,
  onApplyDraftPatch,
  onTopicSelect,
  selectingTopicId,
}: {
  message: Message;
  onApplyDraftPatch: (patch: WorkshopDraftPatchProposal) => void;
  onTopicSelect: (topicId: string, subject: string) => void;
  selectingTopicId: string | null;
}) {
  const isUser = message.role === 'user';
  const isStreaming = !isUser && !message.content;

  return (
    <div className={cn("flex gap-3", isUser && "flex-row-reverse")}>
      <div
        className={cn(
          "flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl text-xs font-black shadow-sm transition-all",
          isUser ? 'bg-slate-100 text-slate-500' : 'bg-[#004aad] text-white shadow-[#004aad]/10'
        )}
      >
        {isUser ? <User size={18} /> : <Bot size={18} />}
      </div>

      <div
        className={cn(
          "relative max-w-[88%] rounded-2xl border px-4 py-3.5 shadow-sm transition-all duration-300 sm:max-w-[80%]",
          isUser 
            ? 'border-[#004aad] bg-[#004aad] text-white shadow-lg shadow-[#004aad]/20' 
            : 'border-slate-200 bg-white text-slate-900 shadow-sm'
        )}
      >
        <div className="flex flex-col gap-1.5">
          {isUser ? (
            <p className="whitespace-pre-wrap text-[15px] font-medium leading-7 text-white">
              {String(message.content || '')}
            </p>
          ) : (
            <MemoizedMarkdown content={String(message.content || '')} role={message.role} />
          )}
          {isStreaming && (
            <div className="flex items-center gap-2 py-1 opacity-70">
              <Loader2 size={12} className="animate-spin text-[#004aad]" />
              <span className="text-[11px] font-bold text-slate-400">Uni Foli가 작성 중..</span>
            </div>
          )}
        </div>

        {message.draftPatch ? (
          <SecondaryButton 
            size="sm" 
            className="mt-3 w-full border-[#004aad]/10 bg-[#004aad]/5 text-[#004aad] hover:bg-[#004aad]/10 shadow-sm" 
            onClick={() => onApplyDraftPatch(message.draftPatch as WorkshopDraftPatchProposal)}
          >
            <Sparkles size={14} className="mr-1.5" />
            섹션 초안 반영
          </SecondaryButton>
        ) : null}

        {message.topicSuggestions?.length ? (
          <div className="mt-4 space-y-2.5">
            <p className="px-1 text-[10px] font-black uppercase tracking-widest text-slate-400">Foli의 추천 주제</p>
            {message.topicSuggestions.map((topic, index) => (
              <button
                key={topic.id}
                type="button"
                onClick={() => onTopicSelect(topic.id, message.topicSubject || '')}
                disabled={Boolean(selectingTopicId)}
                className="group w-full rounded-2xl border border-slate-100 bg-slate-50/80 p-3.5 text-left transition-all hover:border-[#004aad]/10 hover:bg-[#004aad]/5 hover:shadow-md disabled:cursor-not-allowed disabled:opacity-60"
              >
                <div className="flex items-center justify-between">
                  <span className="inline-flex items-center justify-center rounded-lg bg-white px-2.5 py-1 text-[10px] font-black text-slate-500 shadow-sm transition-colors group-hover:bg-[#004aad] group-hover:text-white">
                    주제 {index + 1}
                  </span>
                  {selectingTopicId === topic.id && <Loader2 size={12} className="animate-spin text-[#004aad]" />}
                </div>
                <p className="mt-2.5 text-[15px] font-bold leading-tight text-slate-900 group-hover:text-[#004aad]">{topic.title}</p>
                <p className="mt-1.5 text-xs font-medium leading-relaxed text-slate-500">
                  {selectingTopicId === topic.id ? '선택한 주제로 초안 섹션을 준비 중입니다...' : '클릭하면 워크숍 초안을 즉시 생성합니다.'}
                </p>
              </button>
            ))}
          </div>
        ) : null}
      </div>
    </div>
  );
});

const WorkshopProgress = ({ 
  requirements, 
  qualityInfo 
}: { 
  requirements: RenderRequirementInfo; 
  qualityInfo?: QualityLevelInfo | null;
}) => {
  const requiredContext = Math.max(1, Math.round(requirements.required_context_score || 1));
  const currentContext = Math.round(requirements.current_context_score || 0);
  const progressPercent = Math.min(100, Math.round((currentContext / requiredContext) * 100));

  const policies = useMemo(() => {
    if (!qualityInfo) return [];
    return [
      { label: 'Authenticity', value: qualityInfo.authenticity_policy },
      { label: 'Guardrail', value: qualityInfo.hallucination_guardrail },
      { label: 'Safety', value: qualityInfo.safety_posture },
    ].filter(p => p.value);
  }, [qualityInfo]);

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between text-[11px] font-black uppercase tracking-widest text-slate-500">
        <span className="flex items-center gap-1.5">
          <Sparkles size={12} className="text-[#004aad]" />
          Drafting Progress
        </span>
        <span className="text-[#004aad]">{progressPercent}%</span>
      </div>
      <div className="h-2 w-full overflow-hidden rounded-full bg-slate-100">
        <motion.div
          initial={{ width: 0 }}
          animate={{ width: `${progressPercent}%` }}
          transition={{ duration: 1, ease: 'easeOut' }}
          className={cn(
            'h-full rounded-full transition-all',
            progressPercent >= 100 ? 'bg-green-500' : 'bg-[#004aad] shadow-[#004aad]/20',
          )}
        />
      </div>
      <div className="grid grid-cols-3 gap-2">
        <div className="rounded-xl bg-slate-50 p-2 text-center">
          <p className="text-[10px] font-bold text-slate-400">턴수</p>
          <p
            className={cn(
              'text-xs font-black',
              requirements.current_turn_count >= requirements.minimum_turn_count ? 'text-green-600' : 'text-slate-700',
            )}
          >
            {requirements.current_turn_count}/{requirements.minimum_turn_count}
          </p>
        </div>
        <div className="rounded-xl bg-slate-50 p-2 text-center">
          <p className="text-[10px] font-bold text-slate-400">근거</p>
          <p
            className={cn(
              'text-xs font-black',
              requirements.current_reference_count >= requirements.minimum_reference_count
                ? 'text-green-600'
                : 'text-slate-700',
            )}
          >
            {requirements.current_reference_count}/{requirements.minimum_reference_count}
          </p>
        </div>
        <div className="rounded-xl bg-slate-50 p-2 text-center">
          <p className="text-[10px] font-bold text-slate-400">맥락</p>
          <p
            className={cn(
              'text-xs font-black',
              currentContext >= requiredContext ? 'text-green-600' : 'text-slate-700',
            )}
          >
            {currentContext}/{requiredContext}
          </p>
        </div>
      </div>

      {qualityInfo && (
        <div className="mt-2 rounded-xl border border-[#004aad]/10 bg-[#004aad]/5 p-3">
          <div className="mb-1.5 flex items-center gap-1.5">
            <ShieldCheck size={12} className="text-[#004aad]" />
            <span className="text-[10px] font-extrabold uppercase tracking-wider text-[#004aad]">
              {qualityInfo.label} Policies Active
            </span>
          </div>
          {policies.length > 0 && (
            <div className="flex flex-wrap gap-1">
              {policies.map((p, idx) => (
                <span
                  key={idx}
                  title={p.value}
                  className="rounded border border-[#004aad]/10 bg-white px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-tighter text-[#004aad]/70"
                >
                  {p.label}
                </span>
              ))}
            </div>
          )}
        </div>
      )}

      {!requirements.can_render && requirements.missing.length > 0 && (
        <p className="mt-2 border-t border-slate-100 pt-2 text-[10px] font-medium leading-relaxed text-slate-400">
          Tip: {requirements.missing[0]} 항목을 보완하면 고품질 렌더링이 가능합니다.
        </p>
      )}
    </div>
  );
};
export function Workshop() {
  const { projectId } = useParams<{ projectId: string }>();
  const location = useLocation();

  const [workshopState, setWorkshopState] = useState<WorkshopStateResponse | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isSessionLoading, setIsSessionLoading] = useState(true);
  const [documentContent, setDocumentContent] = useState('');
  const [qualityLevel, setQualityLevel] = useState<QualityLevel>('mid');
  const [advancedMode, setAdvancedMode] = useState(false);
  const [renderArtifact, setRenderArtifact] = useState<DraftArtifact | null>(null);
  const [latestDraftUpdatedAt, setLatestDraftUpdatedAt] = useState<string | null>(null);
  const [isDraftOutOfSync, setIsDraftOutOfSync] = useState(false);
  const [workshopMode, setWorkshopMode] = useState<WorkshopMode>('planning');
  const [showDraftControls, setShowDraftControls] = useState(false);
  const [showAdvancedTools, setShowAdvancedTools] = useState(false);
  const [structuredDraft, setStructuredDraft] = useState<WorkshopStructuredDraftState>(() =>
    createEmptyStructuredDraft('planning'),
  );
  const [pendingDraftPatch, setPendingDraftPatch] = useState<WorkshopDraftPatchProposal | null>(null);

  const [diagnosisReport, setDiagnosisReport] = useState<Record<string, unknown> | null>(null);
  const [showDiagnosis, setShowDiagnosis] = useState(false);
  const [isRendering, setIsRendering] = useState(false);
  const [guidedSubject, setGuidedSubject] = useState<string | null>(null);
  const [guidedSuggestions, setGuidedSuggestions] = useState<GuidedTopicSuggestion[]>([]);
  const [isGuidedTopicSelected, setIsGuidedTopicSelected] = useState(false);
  const [isSelectingGuidedTopicId, setIsSelectingGuidedTopicId] = useState<string | null>(null);
  const [chatMeta, setChatMeta] = useState<StreamMetaPayload | null>(null);
  const [mobileView, setMobileView] = useState<'chat' | 'draft'>('chat');
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const questStart = useMemo(() => readQuestStart(), []);
  const initialMajor = useMemo(
    () => ((location.state as { major?: string } | null)?.major || 'Undecided'),
    [location.state],
  );
  const isProjectBacked = Boolean(projectId && projectId !== 'demo');
  const guidedProjectId = isProjectBacked ? projectId ?? null : null;
  const fileName = useMemo(() => `${(questStart?.title || 'draft').replace(/\s+/g, '_')}.hwpx`, [questStart]);

  const initWorkshop = useCallback(async () => {
    setIsSessionLoading(true);
    setGuidedSubject(null);
    setGuidedSuggestions([]);
    setIsGuidedTopicSelected(false);
    setIsSelectingGuidedTopicId(null);
    setChatMeta(null);
    setLatestDraftUpdatedAt(null);
    setIsDraftOutOfSync(false);
    setPendingDraftPatch(null);
    setShowDraftControls(false);
    setShowAdvancedTools(false);
    setWorkshopMode('planning');
    setStructuredDraft(createEmptyStructuredDraft('planning'));
    try {
      const sessions = await api.get<WorkshopSessionResponse[]>(`/api/v1/workshops?project_id=${projectId}`);
      const active = sessions.find(session => session.status !== 'completed');
      const preferredQuality = localStorage.getItem('uni_foli_quality_level');
      const createQuality: QualityLevel =
        preferredQuality === 'low' || preferredQuality === 'mid' || preferredQuality === 'high'
          ? preferredQuality
          : 'mid';
      const state = active
        ? await api.get<WorkshopStateResponse>(`/api/v1/workshops/${active.id}`)
        : await api.post<WorkshopStateResponse>('/api/v1/workshops', { project_id: projectId, quality_level: createQuality });

      setWorkshopState(state);
      setQualityLevel(state.session.quality_level);

      if (state.latest_artifact) {
        setRenderArtifact(state.latest_artifact);
        const fromArtifact =
          normalizeStructuredDraft(
            state.latest_artifact.structured_draft ||
              state.latest_artifact.evidence_map?.coauthoring?.structured_draft,
          ) ||
          markdownToStructuredDraft(String(state.latest_artifact.report_markdown || ''), 'planning');
        setStructuredDraft(fromArtifact);
        setWorkshopMode(fromArtifact.mode);
        setDocumentContent(structuredDraftToMarkdown(fromArtifact));
        setLatestDraftUpdatedAt(state.latest_artifact.updated_at ?? null);
        setIsDraftOutOfSync(false);
      }

      const turns = state.session.turns || [];
      const loadedMessages: Message[] = [];
      turns.forEach(turn => {
        const role: MessageRole = (turn.speaker_role === 'assistant' || turn.speaker_role === 'bot') ? 'foli' : 'user';
        const content = (role === 'foli' ? (turn.response || turn.query) : turn.query) || '';
        const draftPatch = normalizeStructuredDraftPatch(turn.action_payload?.draft_patch);
        
        if (role === 'foli') {
          loadedMessages.push({ id: turn.id, role: 'foli', content, draftPatch: draftPatch || undefined });
        } else {
          loadedMessages.push({ id: turn.id, role: 'user', content });
          if (turn.response) {
            loadedMessages.push({ id: `${turn.id}-A`, role: 'foli', content: turn.response });
          }
        }
      });

      if (loadedMessages.length) {
        setMessages(loadedMessages);
        setIsGuidedTopicSelected(true);
      } else {
        try {
          const guidedStart = await api.post<GuidedChatStartResponse>('/api/v1/guided-chat/start', {
            project_id: projectId,
          });
          const greeting = (guidedStart.greeting || GUIDED_CHAT_GREETING).trim();
          const greetingMessage = guidedStart.evidence_gap_note ? `${greeting}\n\n${guidedStart.evidence_gap_note}` : greeting;
          const stateSummary = guidedStart.state_summary || {};
          const cachedStarter =
            typeof stateSummary.starter_draft_markdown === 'string' && stateSummary.starter_draft_markdown.trim()
              ? stateSummary.starter_draft_markdown
              : null;
          const cachedSubject =
            typeof stateSummary.subject === 'string' && stateSummary.subject.trim()
              ? stateSummary.subject
              : null;
          const cachedSelectedTopic =
            typeof stateSummary.selected_topic === 'string' && stateSummary.selected_topic.trim()
              ? stateSummary.selected_topic
              : null;

          if (guidedStart.limited_mode) {
            setChatMeta({
              profile: 'standard',
              limited_mode: true,
              limited_reason: guidedStart.limited_reason || 'limited_context',
            });
          }
          if (cachedSubject) {
            setGuidedSubject(cachedSubject);
          }
          if (cachedStarter && !state.latest_artifact) {
            const derived = markdownToStructuredDraft(cachedStarter, 'planning');
            setStructuredDraft(derived);
            setWorkshopMode(derived.mode);
            setDocumentContent(structuredDraftToMarkdown(derived));
            setIsGuidedTopicSelected(true);
            setMessages([
              { id: 'init', role: 'foli', content: greetingMessage },
              {
                id: 'guided-resume',
                role: 'foli',
                content: cachedSelectedTopic
                  ? `저장된 주제 '${cachedSelectedTopic}' 초안을 불러왔습니다. 이어가며 보강해 보세요`
                  : '저장된 초안을 불러왔습니다. 이어가며 보강해 보세요',
              },
            ]);
          } else {
            setMessages([{ id: 'init', role: 'foli', content: greetingMessage }]);
          }
        } catch {
          setMessages([{ id: 'init', role: 'foli', content: GUIDED_CHAT_GREETING }]);
        }
      }

      api.get<{ result_payload?: Record<string, unknown> }>(`/api/v1/diagnosis/project/${projectId}/latest`)
        .then(res => {
          if (res?.result_payload) {
            setDiagnosisReport(res.result_payload);
            setShowDiagnosis(true);
          }
        })
        .catch(() => {});
    } catch (error) {
      console.error('Workshop init failed:', error);
      toast.error('워크숍을 불러오지 못했습니다. 로컬 모드로 전환합니다.');
      setIsGuidedTopicSelected(true);
      setMessages([{ id: 'fallback', role: 'foli', content: '세션 연결에 실패했습니다. 로컬에서 초안 작성을 진행하실 수 있습니다.' }]);
    } finally {
      setIsSessionLoading(false);
    }
  }, [projectId]);

  useEffect(() => {
    const savedLevel = localStorage.getItem('uni_foli_quality_level');
    if (savedLevel === 'low' || savedLevel === 'mid' || savedLevel === 'high') {
      setQualityLevel(savedLevel as QualityLevel);
    }
    if (!documentContent) {
      const seed =
        questStart?.document_seed_markdown ||
        `# [연구 초안] ${questStart?.title || '새 주제'}\n\n## Introduction / Background\n\n## Body Section 1\n\n## Body Section 2\n\n## Body Section 3\n\n## Conclusion / Reflection / Next Step`;
      const derived = markdownToStructuredDraft(seed, 'planning');
      setStructuredDraft(derived);
      setWorkshopMode(derived.mode);
      setDocumentContent(structuredDraftToMarkdown(derived));
    }

    if (isProjectBacked) {
      void initWorkshop();
    } else {
      setIsSessionLoading(false);
      setIsGuidedTopicSelected(true);
      setMessages([{ id: 'demo-init', role: 'foli', content: '데모 모드입니다. Uni Foli에게 질문하면 초안 작성을 도와드립니다.' }]);
    }
  }, [initialMajor, isProjectBacked, initWorkshop, questStart, documentContent]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const saveDraftWithSync = useCallback(
    async (content: string, expectedUpdatedAt: string | null, retryOnConflict = true) => {
      if (!workshopState?.session.id) return;

      const attemptSave = async (
        nextContent: string,
        nextExpectedUpdatedAt: string | null,
        canRetry: boolean,
      ): Promise<void> => {
        try {
          const saved = await api.put<WorkshopSaveDraftResponse>(
            `/api/v1/workshops/${workshopState.session.id}/drafts/latest`,
            {
              document_content: nextContent,
              expected_updated_at: nextExpectedUpdatedAt ?? undefined,
              mode: workshopMode,
              structured_draft: structuredDraft,
            },
          );
          setLatestDraftUpdatedAt(saved.saved_updated_at);
          if (saved.structured_draft) {
            const normalized = normalizeStructuredDraft(saved.structured_draft, workshopMode);
            if (normalized) {
              setStructuredDraft(normalized);
              setWorkshopMode(normalized.mode);
            }
          }
          setIsDraftOutOfSync(false);
          return;
        } catch (error: any) {
          const conflictDetail = error?.response?.status === 409 ? error?.response?.data?.detail : null;
          if (
            canRetry &&
            conflictDetail &&
            typeof conflictDetail === 'object' &&
            typeof conflictDetail.latest_document_content === 'string' &&
            typeof conflictDetail.latest_updated_at === 'string'
          ) {
            const remoteContent = String(conflictDetail.latest_document_content || '');
            const remoteUpdatedAt = String(conflictDetail.latest_updated_at || '');
            const remoteStructured = normalizeStructuredDraft(
              conflictDetail.latest_structured_draft,
              workshopMode,
            );
            const mergedContent =
              remoteContent.trim() === nextContent.trim() || remoteContent.includes(nextContent.trim())
                ? remoteContent
                : `${remoteContent}\n\n${nextContent}`;

            setDocumentContent(mergedContent);
            if (remoteStructured) {
              setStructuredDraft(remoteStructured);
              setWorkshopMode(remoteStructured.mode);
            } else {
              const mergedStructured = markdownToStructuredDraft(mergedContent, workshopMode);
              setStructuredDraft(mergedStructured);
            }
            setLatestDraftUpdatedAt(remoteUpdatedAt);
            setIsDraftOutOfSync(true);
            toast('Draft changed in another tab. We merged your latest edits and re-saved.');
            await attemptSave(mergedContent, remoteUpdatedAt, false);
            return;
          }
          console.error('Autosave failed:', error);
        }
      };

      await attemptSave(content, expectedUpdatedAt, retryOnConflict);
    },
    [workshopState?.session.id, structuredDraft, workshopMode],
  );

  useEffect(() => {
    if (!workshopState?.session.id || !documentContent) return;
    const timeout = setTimeout(() => {
      void saveDraftWithSync(documentContent, latestDraftUpdatedAt);
    }, 3000);
    return () => clearTimeout(timeout);
  }, [documentContent, latestDraftUpdatedAt, saveDraftWithSync, workshopState?.session.id]);

  useEffect(() => {
    const nextMarkdown = structuredDraftToMarkdown(structuredDraft);
    if (nextMarkdown !== documentContent) {
      setDocumentContent(nextMarkdown);
    }
  }, [structuredDraft, documentContent]);


  const handleGuidedTopicSelection = useCallback(
    async (topicId: string, subjectFromMessage?: string) => {
      if (!guidedSuggestions.length || !guidedProjectId) return;

      setIsSelectingGuidedTopicId(topicId);
      try {
        const response = await api.post<GuidedTopicSelectionResponse>('/api/v1/guided-chat/topic-selection', {
          project_id: guidedProjectId,
          selected_topic_id: topicId,
          subject: subjectFromMessage || guidedSubject || undefined,
          suggestions: guidedSuggestions,
        });
        if (response.limited_mode) {
          setChatMeta({
            profile: 'fast',
            limited_mode: true,
            limited_reason: response.limited_reason || 'limited_context',
          });
        }
        const derived = markdownToStructuredDraft(response.starter_draft_markdown, 'outline');
        setStructuredDraft(derived);
        setWorkshopMode(derived.mode);
        setDocumentContent(structuredDraftToMarkdown(derived));
        setLatestDraftUpdatedAt(null);
        setIsDraftOutOfSync(false);
        setIsGuidedTopicSelected(true);
        setMessages(prev => [...prev, { id: crypto.randomUUID(), role: 'foli', content: formatGuidedSelectionMessage(response) }]);
        toast.success('선택한 주제 기준으로 프로젝트를 구성했습니다.');
      } catch (error) {
        console.error('Guided topic selection failed:', error);
        toast.error('주제 선택 반영에 실패했습니다.');
      } finally {
        setIsSelectingGuidedTopicId(null);
      }
    },
    [guidedProjectId, guidedSubject, guidedSuggestions],
  );

  const requestGuidedSuggestions = useCallback(
    async (subjectText: string) => {
      if (!guidedProjectId) return;
      const pendingId = crypto.randomUUID();
      setMessages(prev => [
        ...prev,
        {
          id: pendingId,
          role: 'foli',
          content: '주제 후보를 빠르게 정리하고 있습니다. 잠시만 기다려 주세요',
        },
      ]);
      try {
        const response = await api.post<GuidedTopicSuggestionResponse>('/api/v1/guided-chat/topic-suggestions', {
          project_id: guidedProjectId,
          subject: subjectText,
        });
        const normalizedSuggestions = normalizeGuidedSuggestions(response);
        if (response.limited_mode) {
          setChatMeta({
            profile: 'fast',
            limited_mode: true,
            limited_reason: response.limited_reason || 'limited_context',
          });
        }
        setGuidedSubject(response.subject);
        setGuidedSuggestions(normalizedSuggestions);
        setMessages(prev => [
          ...prev.map(message =>
            message.id === pendingId
              ? {
                  ...message,
                  content: formatGuidedSuggestionMessage(response),
                  topicSubject: response.subject,
                  topicSuggestions: normalizedSuggestions,
                }
              : message,
          ),
        ]);
      } catch (error) {
        setMessages(prev => prev.filter(message => message.id !== pendingId));
        throw error;
      }
    },
    [guidedProjectId],
  );

  const coauthoringTier = useMemo<'basic' | 'plus' | 'pro'>(() => {
    if (qualityLevel === 'high') return 'pro';
    if (qualityLevel === 'mid') return 'plus';
    return 'basic';
  }, [qualityLevel]);

  const applyPatchToDraft = useCallback(
    (patch: WorkshopDraftPatchProposal, approved: boolean, allowOverwriteStudentContent = false) => {
      let applied = false;
      let blockedReason: string | undefined;
      setStructuredDraft((prev) => {
        const result = applyDraftPatch(prev, patch, {
          approved,
          allowOverwriteStudentContent,
        });
        applied = result.applied;
        blockedReason = result.blockedReason;
        if (result.applied) {
          setWorkshopMode(result.next.mode);
        }
        return result.next;
      });
      if (applied) {
        setPendingDraftPatch(null);
        if (approved) {
          toast.success('승인된 섹션 제안을 우측 구조 초안에 반영했습니다.');
        }
      } else if (blockedReason === 'student_content_protected') {
        toast('학생이 직접 작성한 섹션이 길어 자동 덮어쓰기를 차단했습니다. 검토 후 수동 반영해 주세요');
      }
      return applied;
    },
    [],
  );

  const updateDraftBlock = useCallback((blockId: string, nextContent: string) => {
    setStructuredDraft((prev) => ({
      ...prev,
      blocks: prev.blocks.map((block) =>
        block.block_id === blockId
          ? {
              ...block,
              content_markdown: nextContent,
              attribution: 'student-authored',
              updated_at: new Date().toISOString(),
            }
          : block,
      ),
    }));
  }, []);

  const updateDraftHeading = useCallback((blockId: string, nextHeading: string) => {
    setStructuredDraft((prev) => ({
      ...prev,
      blocks: prev.blocks.map((block) =>
        block.block_id === blockId
          ? {
              ...block,
              heading: nextHeading || block.heading,
              attribution: block.attribution,
              updated_at: new Date().toISOString(),
            }
          : block,
      ),
    }));
  }, []);

  const handleSend = async (overriddenText?: string) => {
    const text = (overriddenText ?? input).trim();
    if (!text || isTyping || isSelectingGuidedTopicId) return;
    if (!overriddenText) setInput('');

    if (pendingDraftPatch && isPatchAcceptanceMessage(text)) {
      applyPatchToDraft(pendingDraftPatch, true, false);
    }

    setMessages(prev => [...prev, { id: crypto.randomUUID(), role: 'user', content: text }]);

    if (isProjectBacked && !isGuidedTopicSelected) {
      const selectedFromText = resolveGuidedSelectionFromText(text, guidedSuggestions);
      if (selectedFromText) {
        await handleGuidedTopicSelection(selectedFromText.id, guidedSubject || undefined);
        return;
      }

      setIsTyping(true);
      try {
        await requestGuidedSuggestions(text);
      } catch (error) {
        console.error('Guided suggestion failed:', error);
        toast.error('주제 제안 생성에 실패했습니다.');
      } finally {
        setIsTyping(false);
      }
      return;
    }

    setIsTyping(true);
    setChatMeta(null);

    const foliId = crypto.randomUUID();
    setMessages(prev => [...prev, { id: foliId, role: 'foli', content: '' }]);

    let accumulated = '';
    let pendingDelta = '';
    let streamedPatch: WorkshopDraftPatchProposal | null = null;
    let flushTimer: number | null = null;

    const flushBufferedDelta = () => {
      if (!pendingDelta) {
        flushTimer = null;
        return;
      }
      accumulated += pendingDelta;
      pendingDelta = '';
      flushTimer = null;
      setMessages(prev => prev.map(message => (message.id === foliId ? { ...message, content: accumulated } : message)));
    };

    try {
      const raw = await streamFoliReply(
        isProjectBacked ? projectId : undefined,
        workshopState?.session.id,
        text,
        documentContent,
        workshopMode,
        structuredDraft,
        delta => {
          pendingDelta += delta;
          if (flushTimer === null) {
            flushTimer = window.setTimeout(flushBufferedDelta, 40);
          }
        },
        meta => {
          setChatMeta(meta);
          if (
            meta.coauthoring_mode === 'planning' ||
            meta.coauthoring_mode === 'outline' ||
            meta.coauthoring_mode === 'section_drafting' ||
            meta.coauthoring_mode === 'revision'
          ) {
            setWorkshopMode(meta.coauthoring_mode);
            setStructuredDraft((prev) => ({ ...prev, mode: meta.coauthoring_mode as WorkshopMode }));
          }
        },
        patch => {
          const normalizedPatch = normalizeStructuredDraftPatch(patch);
          if (normalizedPatch) {
            streamedPatch = normalizedPatch;
            setPendingDraftPatch(normalizedPatch);
          }
        },
      );

      if (flushTimer !== null) {
        window.clearTimeout(flushTimer);
        flushTimer = null;
      }
      flushBufferedDelta();

      const extracted = extractPatchTagFromRaw(raw);
      const resolvedPatch = streamedPatch || extracted.patch;
      const responseContent = extracted.cleaned || raw || accumulated || '응답을 생성하지 못했습니다.';
      const shouldAutoApplyPatch =
        resolvedPatch !== null &&
        coauthoringTier !== 'basic' &&
        (isPatchAcceptanceMessage(text) || isSectionDraftIntent(text));

      if (resolvedPatch && shouldAutoApplyPatch) {
        const autoApplied = applyPatchToDraft(resolvedPatch, true, false);
        if (!autoApplied) {
          setPendingDraftPatch(resolvedPatch);
        }
      }

      setMessages(prev =>
        prev.map(message =>
          message.id === foliId
            ? {
                ...message,
                content: responseContent,
                draftPatch: resolvedPatch && !shouldAutoApplyPatch ? resolvedPatch : undefined,
              }
            : message,
        ),
      );
    } catch (error) {
      console.error('AI reply stream failed:', error);
      toast.error('대화 중 오류가 발생했습니다.');
    } finally {
      setIsTyping(false);
    }
  };

  const handleApplyPatchFromMessage = useCallback(
    (patch: WorkshopDraftPatchProposal) => {
      setPendingDraftPatch(patch);
      applyPatchToDraft(patch, true, false);
    },
    [applyPatchToDraft],
  );

  const handleGenerateDraft = async () => {
    if (!workshopState || isRendering) return;
    setIsRendering(true);
    try {
      await api.post(`/api/v1/workshops/${workshopState.session.id}/render`);
      toast.success('결과물 생성을 요청했습니다.');
    } catch (error) {
      console.error('Failed to render draft:', error);
      toast.error('생성 요청에 실패했습니다.');
    } finally {
      setIsRendering(false);
    }
  };

  const handleSaveDraft = () => {
    saveArchiveItem({
      id: crypto.randomUUID(),
      projectId: projectId ?? null,
      title: fileName.replace('.hwpx', ''),
      subject: initialMajor,
      createdAt: new Date().toISOString(),
      contentMarkdown: documentContent,
    });
    toast.success('워크숍 초안을 저장했습니다.');
    confetti({ particleCount: 80, spread: 62, origin: { y: 0.65 } });
  };

  const handleUpdateVisualStatus = async (visualId: string, status: string) => {
    if (!workshopState?.session.id || !workshopState.latest_artifact?.id) return;
    try {
      const response = await api.patch(
        `/api/v1/workshops/${workshopState.session.id}/artifacts/${workshopState.latest_artifact.id}/visuals/${visualId}`,
        { approval_status: status }
      );
      setWorkshopState(response.data);
      toast.success('상태를 업데이트했습니다.');
    } catch (error) {
      console.error('Failed to update visual status:', error);
      toast.error('상태 업데이트 실패');
    }
  };

  const handleReplaceVisual = async (visualId: string) => {
    if (!workshopState?.session.id || !workshopState.latest_artifact?.id) return;
    try {
      const response = await api.post(
        `/api/v1/workshops/${workshopState.session.id}/artifacts/${workshopState.latest_artifact.id}/visuals/${visualId}/replace`
      );
      setWorkshopState(response.data);
      toast.success('새로운 시각 자료를 생성했습니다.');
    } catch (error) {
      console.error('Failed to replace visual:', error);
      toast.error('시각 자료 생성 실패');
    }
  };

  const qualityMeta = QUALITY_META_MAP[qualityLevel];
  const diagnosisSummary = (diagnosisReport?.summary ?? {}) as {
    headline?: string;
    risk_level?: string;
    gaps?: unknown[];
  };
  const diagnosisHeadline = diagnosisSummary.headline;
  const diagnosisRisk = diagnosisSummary.risk_level;
  const diagnosisGapCount = diagnosisSummary.gaps?.length || 0;
  const inputPlaceholder = isProjectBacked && !isGuidedTopicSelected
    ? '관심 과목이나 주제를 입력해 주세요'
    : '메시지를 입력하세요...';

  return (
    <div className={cn("mx-auto max-w-[1800px] space-y-4 px-2.5 py-3 transition-all duration-700 sm:space-y-6 sm:px-4 sm:py-6", advancedMode && "rounded-[32px] bg-[#004aad]/5 shadow-[inset_0_0_100px_rgba(0,74,173,0.02)] sm:rounded-[48px]")}>
      <motion.div
        animate={advancedMode ? { y: [0, -2, 0] } : {}}
        transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
      >
        <PageHeader
          eyebrow="Workshop"
          title="Uni Foli Draft Workspace"
          description="Continue drafting with grounded guidance from your uploaded records."
          actions={
            <div className="flex items-center gap-2">
              <SecondaryButton
                data-testid="workshop-advanced-toggle"
                onClick={() => setAdvancedMode(prev => !prev)}
                aria-label={advancedMode ? 'Disable advanced mode' : 'Enable advanced mode'}
              >
                {advancedMode ? <ToggleRight size={16} /> : <ToggleLeft size={16} />}
                {advancedMode ? 'Advanced mode' : 'Basic mode'}
              </SecondaryButton>
              <SecondaryButton
                onClick={handleGenerateDraft}
                disabled={!workshopState || isRendering || !workshopState.render_requirements?.can_render}
              >
                {isRendering ? <Loader2 size={16} className="animate-spin" /> : <WandSparkles size={16} />}
                Render preview
              </SecondaryButton>
            </div>
          }
          evidence={
            <div className="flex flex-wrap items-center gap-2">
              <StatusBadge status={isProjectBacked ? 'success' : 'warning'}>
                {isProjectBacked ? 'Project connected' : 'Demo mode'}
              </StatusBadge>
              {isProjectBacked && (
                <StatusBadge status={isGuidedTopicSelected ? 'success' : 'warning'}>
                  {isGuidedTopicSelected ? 'Topic selected' : 'Topic pending'}
                </StatusBadge>
              )}
              <StatusBadge status={qualityMeta.status}>{qualityMeta.label}</StatusBadge>
            </div>
          }
        />

        <div className="mt-6 lg:hidden">
          <div className="inline-flex w-full items-center gap-1 rounded-2xl border border-slate-200 bg-white p-1 shadow-sm">
            <button
              type="button"
              onClick={() => setMobileView('chat')}
              className={cn(
                'h-10 flex-1 rounded-xl px-3 text-sm font-bold transition-all',
                mobileView === 'chat' ? 'bg-[#004aad] text-white shadow-md' : 'text-slate-600 hover:bg-slate-50',
              )}
            >
              채팅
            </button>
            <button
              type="button"
              onClick={() => setMobileView('draft')}
              className={cn(
                'h-10 flex-1 rounded-xl px-3 text-sm font-bold transition-all',
                mobileView === 'draft' ? 'bg-[#004aad] text-white shadow-md' : 'text-slate-600 hover:bg-slate-50',
              )}
            >
              문서
            </button>
          </div>
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-[400px_minmax(0,1fr)] xl:grid-cols-[460px_minmax(0,1fr)]">
          <SectionCard
            title="Uni Foli Chat"
            eyebrow="Chat"
            className={cn(
              'flex min-h-0 flex-col h-[calc(100dvh-15rem)] min-h-[520px] max-h-[800px]',
              mobileView !== 'chat' && 'hidden lg:flex'
            )}
            bodyClassName="relative flex min-h-0 flex-1 flex-col overflow-hidden p-0"
          >
            <div className="flex h-full flex-col">
              <div className="flex-1 overflow-y-auto px-4 py-4 space-y-6 scroll-smooth">
                {workshopState?.render_requirements && (
                  <div className="mb-2 border-b border-slate-100 bg-slate-50/30 px-4 py-4">
                    <WorkshopProgress 
                      requirements={workshopState.render_requirements} 
                      qualityInfo={workshopState.quality_level_info}
                    />
                  </div>
                )}

                {diagnosisReport && (
                  <SurfaceCard tone="muted" padding="none" className="mb-4 overflow-hidden border-[#004aad]/10 bg-[#004aad]/5">
                    <button
                      type="button"
                      onClick={() => setShowDiagnosis(prev => !prev)}
                      className="flex w-full items-center justify-between px-4 py-3 text-left text-sm font-bold text-slate-700 hover:bg-[#004aad]/10"
                    >
                      <span className="inline-flex items-center gap-2">
                        <div className="h-1.5 w-1.5 rounded-full bg-[#004aad] shadow-sm shadow-[#004aad]/50" />
                        최근 생기부 진단 정보
                      </span>
                      {showDiagnosis ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                    </button>
                    <AnimatePresence>
                      {showDiagnosis && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          className="overflow-hidden border-t border-[#004aad]/10 px-4 pb-4"
                        >
                          <SurfaceCard padding="sm" className="mt-3 space-y-2 border-none bg-white/60">
                            <p className="text-sm font-bold text-slate-900">{diagnosisHeadline}</p>
                            <div className="flex flex-wrap items-center gap-2">
                              {diagnosisRisk && <StatusBadge status={diagnosisRisk === 'safe' ? 'success' : 'warning'}>{diagnosisRisk}</StatusBadge>}
                              <StatusBadge status="neutral">보완 {diagnosisGapCount}</StatusBadge>
                            </div>
                          </SurfaceCard>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </SurfaceCard>
                )}

                {chatMeta?.limited_mode && (
                  <WorkflowNotice
                    tone="warning"
                    title="Limited mode is active"
                    description="The model connection is unstable, so fallback assistance is being used for this turn."
                    className="mb-4"
                  />
                )}

                {isProjectBacked && !isGuidedTopicSelected && (
                  <WorkflowNotice
                    tone="info"
                    title="Topic selection required"
                    description="Enter your preferred area first so Uni Foli can suggest grounded topics."
                    className="mb-4"
                  />
                )}

                {!isSessionLoading ? (
                  <div className="space-y-6 pb-4">
                    {messages.map((message) => (
                      <ChatBubble
                        key={message.id}
                        message={message}
                        onApplyDraftPatch={handleApplyPatchFromMessage}
                        onTopicSelect={handleGuidedTopicSelection}
                        selectingTopicId={isSelectingGuidedTopicId}
                      />
                    ))}
                    <div ref={messagesEndRef} />
                  </div>
                ) : (
                  <div className="flex h-full items-center justify-center py-20">
                    <Loader2 size={24} className="animate-spin text-[#004aad]" />
                  </div>
                )}
              </div>

              <div className="border-t border-slate-100 bg-white p-4">
                <div className="flex items-center gap-3">
                  <input
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' && !e.shiftKey) {
                        e.preventDefault();
                        void handleSend();
                      }
                    }}
                    placeholder={inputPlaceholder}
                    disabled={isTyping || !!isSelectingGuidedTopicId}
                    className="flex-1 h-12 rounded-2xl border-2 border-slate-200 bg-slate-50 px-4 text-[15px] font-medium text-slate-900 outline-none transition-all placeholder:text-slate-400 focus:border-[#004aad] disabled:opacity-50"
                  />
                  <button
                    type="button"
                    onClick={() => void handleSend()}
                    disabled={!input.trim() || isTyping || !!isSelectingGuidedTopicId}
                    className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#004aad] text-white shadow-lg shadow-[#004aad]/20 transition-all hover:bg-[#003a8a] disabled:bg-slate-200"
                  >
                    {isTyping ? <Loader2 size={20} className="animate-spin" /> : <Send size={20} />}
                  </button>
                </div>
              </div>
            </div>
          </SectionCard>

          <SectionCard
            title="초안 문서"
            description="Uni Foli가 제안한 내용을 바탕으로 구성된 문서입니다. 자유롭게 수정하며 보강하세요"
            eyebrow="Drafting"
            className={cn(
              'flex min-h-0 flex-col h-[calc(100dvh-15rem)] min-h-[520px] max-h-[800px]',
              mobileView !== 'draft' && 'hidden lg:flex'
            )}
            bodyClassName="flex min-h-0 flex-1 flex-col overflow-hidden p-0"
            actions={
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setShowDraftControls(prev => !prev)}
                  className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold text-slate-600 transition-colors hover:bg-slate-50"
                >
                  {showDraftControls ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                  Draft options
                </button>
                <PrimaryButton size="sm" onClick={handleSaveDraft}>
                  <Save size={14} className="mr-1.5" />
                  Save
                </PrimaryButton>
                <SecondaryButton size="sm" onClick={() => {
                  const blob = new Blob([documentContent], { type: 'text/markdown' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = fileName.replace('.hwpx', '.md');
                  a.click();
                  URL.revokeObjectURL(url);
                }}>
                  <Download size={14} className="mr-1.5" />
                  Markdown
                </SecondaryButton>
              </div>
            }
          >
            <div className={cn("flex flex-1 flex-col overflow-hidden p-3 sm:p-4", advancedMode && "lg:flex-row gap-4")}>
              {isDraftOutOfSync ? (
                <WorkflowNotice
                  tone="warning"
                  title="Draft sync conflict detected"
                  description="The latest server version was merged and saved again. Please quickly review the merged draft."
                  className="mb-3"
                />
              ) : null}

              {pendingDraftPatch ? (
                <SurfaceCard tone="muted" className="mb-3 border-[#004aad]/10 bg-[#004aad]/5 p-3">
                  <p className="text-xs font-black uppercase tracking-wide text-[#004aad]">Pending section proposal</p>
                  <p className="mt-1 text-sm font-bold text-slate-900">
                    {pendingDraftPatch.heading || pendingDraftPatch.block_id}
                  </p>
                  {pendingDraftPatch.rationale ? (
                    <p className="mt-1 text-xs font-medium text-slate-600">{pendingDraftPatch.rationale}</p>
                  ) : null}
                  {pendingDraftPatch.evidence_boundary_note ? (
                    <p className="mt-1 text-xs font-semibold text-amber-700">
                      근거 경계: {pendingDraftPatch.evidence_boundary_note}
                    </p>
                  ) : null}
                  <div className="mt-2 flex items-center gap-2">
                    <PrimaryButton size="sm" onClick={() => applyPatchToDraft(pendingDraftPatch, true, false)}>
                      Apply to Draft
                    </PrimaryButton>
                    <SecondaryButton size="sm" onClick={() => setPendingDraftPatch(null)}>
                      Keep as Suggestion
                    </SecondaryButton>
                  </div>
                </SurfaceCard>
              ) : null}

              {showDraftControls ? (
                <div className={cn("space-y-3", advancedMode && "lg:w-1/2")}>
                  <div className="grid gap-2 sm:grid-cols-4">
                    {WORKSHOP_MODE_OPTIONS.map((option, idx) => (
                      <button
                        key={option.id}
                        type="button"
                        onClick={() => {
                          setWorkshopMode(option.id);
                          setStructuredDraft((prev) => ({ ...prev, mode: option.id }));
                        }}
                        className={cn(
                          'p-2.5 rounded-xl border transition-all text-xs font-semibold text-left',
                          workshopMode === option.id
                            ? 'border-[#004aad]/20 bg-[#004aad]/5 shadow-sm'
                            : 'border-slate-200 bg-white hover:border-slate-300',
                        )}
                      >
                        <p className="text-xs font-black text-slate-800">{option.label}</p>
                        <p className="mt-0.5 text-[11px] font-medium leading-4 text-slate-500">{option.description}</p>
                      </button>
                    ))}
                  </div>

                  <WorkflowNotice
                    tone={coauthoringTier === 'pro' ? 'success' : coauthoringTier === 'plus' ? 'info' : 'warning'}
                    title={
                      coauthoringTier === 'pro'
                        ? 'Pro Co-authoring'
                        : coauthoringTier === 'plus'
                          ? 'Plus Co-authoring'
                          : 'Basic Co-authoring'
                    }
                    description={
                      coauthoringTier === 'basic'
                        ? 'AI 제안은 승인 시 반영됩니다. 학생 작성 내용은 자동 덮어쓰기되지 않습니다.'
                        : '채팅 중 섹션 제안을 실시간으로 연결합니다. 승인 전에는 학생 작성 문단을 보호합니다.'
                    }
                  />
                </div>
              ) : (
                <p className={cn('text-xs font-semibold text-slate-500', advancedMode && 'lg:w-1/2')}>
                  Draft options are hidden. Expand only when you need mode or tier controls.
                </p>
              )}

              <div
                className={cn(
                  "mt-3 w-full min-h-0 flex-1 space-y-3 overflow-y-auto pr-1 custom-scrollbar",
                  advancedMode && "lg:w-1/2",
                )}
              >
                {BLOCK_DEFINITIONS.map((definition) => {
                  const block =
                    structuredDraft.blocks.find((item) => item.block_id === definition.id) || {
                      block_id: definition.id,
                      heading: definition.heading,
                      content_markdown: '',
                      attribution: 'student-authored' as WorkshopDraftAttribution,
                    };
                  const attributionStatus =
                    block.attribution === 'student-authored'
                      ? 'success'
                      : block.attribution === 'ai-inserted-after-approval'
                        ? 'active'
                        : 'warning';
                  return (
                    <SurfaceCard key={definition.id} className="border-slate-200 bg-white p-3 shadow-sm">
                      <div className="mb-2 flex items-center justify-between gap-2">
                        <input
                          value={block.heading}
                          onChange={(event) => updateDraftHeading(definition.id, event.target.value)}
                          className="w-full rounded-lg border border-slate-200 bg-slate-50 px-2 py-1.5 text-xs font-bold text-slate-800 outline-none focus:border-[#004aad] focus:bg-white"
                        />
                        <StatusBadge status={attributionStatus}>
                          {block.attribution}
                        </StatusBadge>
                      </div>
                      {definition.id === 'title' ? (
                        <input
                          value={block.content_markdown}
                          onChange={(event) => updateDraftBlock(definition.id, event.target.value)}
                          placeholder="Title"
                          className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm font-semibold text-slate-800 outline-none focus:border-[#004aad] focus:bg-white"
                        />
                      ) : (
                        <textarea
                          value={block.content_markdown}
                          onChange={(event) => updateDraftBlock(definition.id, event.target.value)}
                          placeholder={`${block.heading} 내용을 작성하세요`}
                          className="min-h-[110px] w-full resize-y rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm font-medium leading-6 text-slate-800 outline-none focus:border-[#004aad] focus:bg-white"
                        />
                      )}
                    </SurfaceCard>
                  );
                })}
              </div>
              
              {advancedMode ? (
                <div className="mt-4 space-y-3 lg:mt-0 lg:w-1/2">
                  <button
                    type="button"
                    onClick={() => setShowAdvancedTools(prev => !prev)}
                    className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold text-slate-600 transition-colors hover:bg-slate-50"
                  >
                    {showAdvancedTools ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                    Advanced tools
                  </button>

                  {showAdvancedTools ? (
                    <div className="flex flex-col gap-4 overflow-y-auto pr-1 custom-scrollbar">
                      <EvidenceDrawer evidenceMap={renderArtifact?.evidence_map ?? null} />
                      <SurfaceCard className="border-[#004aad]/5 bg-[#004aad]/5 p-4 shadow-sm">
                        <AdvancedPreview
                          workshopId={workshopState?.session.id || ''}
                          artifactId={workshopState?.latest_artifact?.id || ''}
                          isAdvancedMode={advancedMode}
                          visualSpecs={renderArtifact?.visual_specs ?? []}
                          mathExpressions={renderArtifact?.math_expressions ?? []}
                          onUpdateVisualStatus={handleUpdateVisualStatus}
                          onReplaceVisual={handleReplaceVisual}
                        />
                      </SurfaceCard>
                    </div>
                  ) : (
                    <p className="text-xs font-semibold text-slate-500">
                      Evidence and render diagnostics are hidden to keep drafting focused.
                    </p>
                  )}
                </div>
              ) : null}
            </div>
          </SectionCard>
        </div>
      </motion.div>
    </div>
  );
}



